version: "3"
services:
  db:
    image: pgvector/pgvector:0.6.0-pg16
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
    tty: true
    stdin_open: true
    healthcheck:
      test: "psql -U postgres -c 'SELECT 1' || exit 1"
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./api
      dockerfile: containers/development/Dockerfile
    command: /bin/bash -c "
      poetry install --no-root;
      python manage.py runserver 0:5000"
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file: .env.local
