# Generated by Django 5.0.1 on 2024-03-22 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, unique=True)),
                ('model_name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Created'), (10, 'Started'), (20, 'Completed'), (30, 'Failed')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='libs.user')),
            ],
            options={
                'verbose_name': '生成タスク',
                'verbose_name_plural': '生成タスク',
                'db_table': 'generation_tasks',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('finish_reason', models.CharField(max_length=256)),
                ('usage', models.JSONField()),
                ('processing_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('messages', models.JSONField()),
                ('category', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='libs.user')),
                ('generation_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='libs.generationtask')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'db_table': 'answers',
            },
        ),
    ]
