# Generated by Django 5.0.1 on 2024-03-22 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0003_generationtask_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('points', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'Created'), (10, 'Started'), (20, 'Completed'), (30, 'Failed')], default=0)),
                ('generation_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_tasks', to='libs.generationtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_tasks', to='libs.user')),
            ],
            options={
                'verbose_name': '評価タスク',
                'verbose_name_plural': '評価タスク',
                'db_table': 'evaluation_tasks',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('finish_reason', models.CharField(max_length=256)),
                ('usage', models.JSONField()),
                ('processing_time', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(999.99)])),
                ('model', models.CharField(max_length=1024)),
                ('point', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='libs.answer')),
                ('evaluation_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='libs.evaluationtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='libs.user')),
            ],
            options={
                'verbose_name': '点数',
                'verbose_name_plural': '点数',
                'db_table': 'rates',
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationtask',
            constraint=models.UniqueConstraint(fields=('generation_task', 'name'), name='evaluation_task_unique'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('evaluation_task', 'answer'), name='rate_unique'),
        ),
    ]
