# Generated by Django 5.0.1 on 2024-03-31 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0004_evaluationtask_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=256)),
                ('worker_count', models.IntegerField()),
                ('parameters', models.JSONField()),
                ('generation_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_setting', to='libs.generationtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_settings', to='libs.user')),
            ],
            options={
                'verbose_name': '生成設定',
                'verbose_name_plural': '生成設定',
                'db_table': 'generation_settings',
            },
        ),
    ]
