# Generated by Django 5.0.1 on 2024-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0006_bench_remove_answer_category_generationtask_bench_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtask',
            name='processing_times',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
