# Generated by Django 5.0.1 on 2024-04-07 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0007_evaluationtask_processing_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4096), default=[], size=None),
            preserve_default=False,
        ),
    ]
