# Generated by Django 5.0.1 on 2024-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0009_bench_template_question_eval_aspects'),
    ]

    operations = [
        migrations.AddField(
            model_name='bench',
            name='code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
