# Generated by Django 5.0.1 on 2024-06-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0010_bench_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='GenerationTaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_task_tags', to='libs.generationtask')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_task_tags', to='libs.tag')),
            ],
            options={
                'verbose_name': '生成タスクタグ',
                'verbose_name_plural': '生成タスクタグ',
                'db_table': 'generation_task_tags',
            },
        ),
        migrations.AddField(
            model_name='generationtask',
            name='tags',
            field=models.ManyToManyField(through='libs.GenerationTaskTag', to='libs.tag'),
        ),
    ]
