# Generated by Django 5.0.1 on 2024-06-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0011_tag_generationtasktag_generationtask_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='function',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
