# Generated by Django 5.0.1 on 2024-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0013_bench_system_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Created'), (10, 'Started'), (20, 'Completed'), (30, 'Failed'), (40, 'Aborted')], default=0),
        ),
    ]
