# Generated by Django 5.0.1 on 2024-06-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0014_alter_generationtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='turn_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bench',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='function',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
