# Generated by Django 5.0.1 on 2024-06-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0015_answer_turn_number_alter_bench_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='libs.answer'),
        ),
        migrations.CreateModel(
            name='RateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_answers', to='libs.answer')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_answers', to='libs.rate')),
            ],
            options={
                'verbose_name': '点数に対する回答',
                'verbose_name_plural': '点数に対する回答',
                'db_table': 'rate_answers',
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='answers',
            field=models.ManyToManyField(through='libs.RateAnswer', to='libs.answer'),
        ),
    ]
