# Generated by Django 5.0.1 on 2024-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0016_alter_rate_answer_rateanswer_rate_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationtask',
            name='plot_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
