# Generated by Django 5.0.1 on 2024-06-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0017_evaluationtask_plot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationtask",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
