# Generated by Django 5.0.1 on 2024-06-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0017_evaluationtask_plot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="subtask",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="task",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
