# Generated by Django 5.0.1 on 2024-07-04 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0019_bench_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=4096), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="eval_aspects",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=4096), blank=True, size=None
            ),
        ),
    ]
