# Generated by Django 5.0.1 on 2024-07-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libs", "0021_evaluationtask_evaluation__active_8c306a_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationtask",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="generationtask",
            index=models.Index(fields=["active"], name="generation__active_14d24e_idx"),
        ),
    ]
